version: "2"

services:

     frontend:
       build: ./frontend
       volumes:
       - ./frontend/www/html/admin/:/var/www/html/admin/:rw
       - ./frontend/sitemap/000-default.conf:/etc/apache2/sites-available/000-default.conf
    #

     backend:
       build: ./backend
       links:
          - db
       volumes:
         - ./backend/app/lms/:/usr/local/tomcat/webapps/lms/
         - ./backend/app/tomcat/tomcat:/etc/init.d/tomcat
         - ./backend/app/tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh:rw
         - ./backend/app/tomcat/conf/db.properties:/usr/local/tomcat/conf/db.properties
#         - ./backend/app/tomcat/conf/:/usr/local/tomcat/conf/
       expose:
         - "8009"
    #

     db:
       build: ./db
       environment:
         MYSQL_ROOT_PASSWORD: Admin11!
         MYSQL_DATABASE: lms
       volumes:
         - ./mysql:/etc/mysql/conf.d
         - ./db/sql:/tmp/database
       command: mysqld --init-file="/tmp/database/create-database.sql"
